import localFont from 'next/font/local'
import './globals.css'
import { ClerkProvider, SignInButton, SignedIn, SignedOut, UserButton } from '@clerk/nextjs'
import Providers from './provider'
import Link from 'next/link'
import { Header } from '@/components/app/Header'

const feather = localFont({
  src: './fonts/FeatherBold.woff',
  variable: '--feather',
  weight: '400 500 700 900',
})
export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${feather.variable} antialiased`}>
        <Providers>
          <Header />

          <main>{children}</main>
        </Providers>
      </body>
    </html>
  )
}
