import localFont from 'next/font/local'
import './globals.css'
import { ClerkProvider, SignInButton, SignedIn, SignedOut, UserButton } from '@clerk/nextjs'
import Providers from './provider'
import Link from 'next/link'

const feather = localFont({
  src: './fonts/FeatherBold.woff',
  variable: '--feather',
  weight: '400 500 700 900',
})
export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <ClerkProvider>
      <html lang="en">
        <body className={`${feather.variable} antialiased`}>
          <Providers>
            <header className='flex justify-between items-center py-2 px-4'>
              <Link href='/' className='text-xl font-bold'>LOGO</Link>
              <div>
                <SignedOut>
                  <SignInButton />
                </SignedOut>
                <SignedIn>
                  <UserButton />
                </SignedIn>
              </div>
            </header>

            <main>{children}</main>
          </Providers>
        </body>
      </html>
    </ClerkProvider>
  )
}
